version: '2'
services:
   db:
      image: percona/percona-server:5.7
      ports:
        - "3306:3306"
      volumes:
        - dbvolume:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=blank
        - MYSQL_ONETIME_PASSWORD=yes
        - MYSQL_DATABASE=presidentlv
        - MYSQL_USER=presidentlv
        - MYSQL_PASSWORD=yQ7JnsaggMHhZP7J
   webserver:
     image: vpk:latest
     # build: .
     volumes:
       - ./webroot:/var/www/html
       - ./sites-enabled:/etc/nginx/sites-enabled
       - ./certs:/etc/ssl/private
       - ./log/nginx:/var/log/nginx
       - ./sqldumps:/root/sqldumps
     command: /root/startup.sh
     # restart: on-failure
     #environment:
     ports:
       - "80:80"
       - "443:443"
     depends_on:
        - db
volumes:
  dbvolume:
